import React,{useEffect,useRef,useState} from 'react';
import type {OfficePdfSnapshot,OfficePdfPage,OfficePdfEditInput} from 'workdsh-contracts/office';
import type {OfficeClient,DocumentOptions} from '../live/model.js';
import {readPdfBytes,downloadPdf} from './download.js';
import {createPdfTask} from './viewer.js';
type Lease={token:string;clientId:string;expiresAt:number};
export function LivePdf({documentId,sessionId,office,visible,signal,requestId,onEditing}:DocumentOptions&{office:OfficeClient;onEditing:(v:boolean)=>void}){
 const [snapshot,setSnapshot]=useState<OfficePdfSnapshot|null>(null),[problem,setProblem]=useState(''),[index,setIndex]=useState(0),[draft,setDraft]=useState<OfficePdfPage|null>(null),[busy,setBusy]=useState(false),[rendered,setRendered]=useState<number|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),visibility=useRef(visible),request=useRef(requestId),lease=useRef<Lease|null>(null),baseline=useRef<OfficePdfSnapshot|null>(null),uncertain=useRef<OfficePdfEditInput|null>(null),clientId=useRef(crypto.randomUUID());visibility.current=visible;request.current=requestId;
 const commands=useRef(new AbortController()),alive=useRef(true);
 useEffect(()=>{commands.current=new AbortController();alive.current=true;return()=>{alive.current=false;commands.current.abort();};},[]);
 const commandSignal=()=>AbortSignal.any([signal,commands.current.signal]);
 const editing=useRef(false);editing.current=!!draft;
 const error=(e:unknown)=>alive.current&&setProblem(e instanceof Error?e.message:String(e));
 useEffect(()=>{const lifetime=new AbortController(),combined=AbortSignal.any([signal,lifetime.signal]);let disposed=false,timer:ReturnType<typeof setTimeout>;
 async function poll(){try{if(visibility.current&&!editing.current){const s=await office.request<OfficePdfSnapshot>(sessionId,{endpoint:'read',documentId},combined);if(disposed)return;if(s.kind!=='pdf')throw Error('不是 PDF 工作副本。');setSnapshot(old=>old?.revision===s.revision&&old.generation===s.generation?old:s);}else if(lease.current){const r=await office.request<{lease:Lease}>(sessionId,{endpoint:'lease',documentId,clientId:clientId.current,action:'renew',token:lease.current.token},combined);if(!disposed)lease.current=r.lease;}}catch(e){if(!disposed&&!combined.aborted)error(e);}finally{if(!disposed)timer=setTimeout(poll,lease.current?8000:700);}}
 void poll();return()=>{disposed=true;lifetime.abort();clearTimeout(timer);onEditing(false);};
 },[documentId,sessionId,office,signal,onEditing]);
 useEffect(()=>{if(!snapshot)return;setIndex(i=>Math.min(i,snapshot.state.pages.length-1));let disposed=false,loading:ReturnType<typeof createPdfTask>|undefined,task:ReturnType<Awaited<ReturnType<typeof createPdfTask>['task']['promise']>['getPage']>|undefined;let render:ReturnType<Awaited<NonNullable<typeof task>>['render']>|undefined;const ctrl=new AbortController(),combined=AbortSignal.any([signal,ctrl.signal]);setRendered(null);
 void(async()=>{try{const bytes=await readPdfBytes(office,sessionId,snapshot,combined);if(disposed)return;loading=createPdfTask(bytes);const doc=await loading.task.promise;const page=await doc.getPage(Math.min(index+1,doc.numPages));if(disposed)return;const view=page.getViewport({scale:1.25}),c=canvas.current;if(!c)return;c.width=view.width;c.height=view.height;render=page.render({canvas:c,viewport:view});await render.promise;if(disposed)return;setRendered(snapshot.revision);const pending=request.current;if(pending)await office.request(sessionId,{endpoint:'ack',documentId,requestId:pending,clientId:clientId.current,appliedRevision:snapshot.revision},combined);setProblem('');}catch(e){if(!disposed&&!combined.aborted)error(e);}})();return()=>{disposed=true;ctrl.abort();render?.cancel();void loading?.destroy();};
 },[snapshot,index,office,sessionId,documentId,signal]);
 async function begin(){if(!snapshot||busy)return;setBusy(true);try{const r=await office.request<{snapshot:OfficePdfSnapshot;lease:Lease}>(sessionId,{endpoint:'lease',documentId,clientId:clientId.current,action:'acquire'},commandSignal());if(!alive.current)return;lease.current=r.lease;baseline.current=r.snapshot;setSnapshot(r.snapshot);setDraft(structuredClone(r.snapshot.state.pages[Math.min(index,r.snapshot.state.pages.length-1)]));onEditing(true);setProblem('');}catch(e){error(e);}finally{if(alive.current)setBusy(false);}}
 async function finish(){if(!draft||!baseline.current||!lease.current||busy)return;setBusy(true);try{if(!uncertain.current)uncertain.current={documentId,baseRevision:baseline.current.revision,operationId:crypto.randomUUID(),operations:[{op:'pdf.updatePage',pageId:draft.id,page:draft}]};await office.request(sessionId,{endpoint:'edit',input:uncertain.current,lease:{token:lease.current.token,clientId:lease.current.clientId}},commandSignal());const saved=await office.request<OfficePdfSnapshot>(sessionId,{endpoint:'read',documentId},commandSignal());await office.request(sessionId,{endpoint:'lease',documentId,clientId:clientId.current,action:'release',token:lease.current.token},commandSignal());if(!alive.current)return;uncertain.current=null;lease.current=null;setDraft(null);setSnapshot(saved);onEditing(false);setProblem('');}catch(e){if(e instanceof Error&&/INVALID_INPUT/.test(e.message))uncertain.current=null;error(e);}finally{if(alive.current)setBusy(false);}}
 async function download(){if(!snapshot)return;try{await downloadPdf(office,sessionId,snapshot,commandSignal());}catch(e){error(e);}}
 return <><div className="wd-office-toolbar"><span className="wd-office-title">{snapshot?.title??'PDF'}</span><span role="status">{draft?'编辑中 · 完成后保存':snapshot?`已保存 · 修订 ${snapshot.revision}${rendered===snapshot.revision?' · 预览已更新':' · 正在渲染'}`:'正在打开…'}</span><button disabled={!snapshot||busy} onClick={()=>void(draft?finish():begin())}>{draft?'完成编辑并保存':'编辑本页文字'}</button><button disabled={!snapshot||!!draft||busy} onClick={()=>void download()}>下载 PDF</button></div><div className="wd-office-status" style={{padding:'6px 12px'}}>支持新建 PDF 的分页文本与矩形；已有 PDF 导入、OCR 与图片编辑尚未接入。</div>{problem&&<div role="alert" className="wd-office-problem">{problem}</div>}{snapshot&&<div style={{padding:8,display:'flex',gap:8,alignItems:'center'}}><button disabled={index===0||!!draft} onClick={()=>setIndex(i=>i-1)}>上一页</button><span>第 {Math.min(index+1,snapshot.state.pages.length)} / {snapshot.state.pages.length} 页</span><button disabled={index>=snapshot.state.pages.length-1||!!draft} onClick={()=>setIndex(i=>i+1)}>下一页</button></div>}{draft&&<div style={{padding:12,maxHeight:300,overflow:'auto'}}>{draft.elements.map((e,i)=>e.type==='text'&&<label key={e.id} style={{display:'block'}}>{e.id}<textarea aria-label={`PDF 文本 ${e.id}`} disabled={busy||!!uncertain.current} value={e.text} onChange={event=>{const text=event.target.value;setDraft(p=>p&&({...p,elements:p.elements.map((el,j)=>j===i&&el.type==='text'?{...el,text}:el)}));}} style={{display:'block',width:'100%',minHeight:70}}/></label>)}</div>}<div style={{flex:1,minHeight:320,overflow:'auto',padding:16,background:'#e5e7eb',textAlign:'center'}}><canvas ref={canvas} aria-label="PDF 实际页面预览" style={{maxWidth:'100%',height:'auto',background:'white'}}/></div></>;
}
