import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {chromium} from '@playwright/test';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const req=createRequire(resolve('packages/plugins/office/package.json')),temp=await mkdtemp(join(tmpdir(),'office-pdf-'));
await build({stdin:{resolveDir:resolve('.'),contents:"export {pdfBytes} from './packages/plugins/office/src/pdf/encode.ts';export {initialPdf} from './packages/plugins/office/src/pdf/model.ts';"},bundle:true,platform:'node',format:'esm',loader:{'.ttf':'binary'},outfile:join(temp,'encode.mjs')});
const {pdfBytes,initialPdf}=await import(pathToFileURL(join(temp,'encode.mjs')));
test('Real Chinese PDF decodes, refreshes preview and downloads final bytes',async()=>{const browser=await chromium.launch({headless:true});try{
 const initial={documentId:'pdf-1',kind:'pdf',title:'预算分析报告',revision:0,generation:'one',state:initialPdf('预算分析报告')};const changed=structuredClone(initial);changed.revision=1;changed.state.pages[0].elements[1].text='年度预算：收入 1000 万元。';const bytes0=await pdfBytes(initial),bytes1=await pdfBytes(changed);assert.equal(Buffer.from(bytes1).subarray(0,5).toString(),'%PDF-');assert.deepEqual(await pdfBytes(changed),bytes1);
 const bundle=await build({stdin:{resolveDir:resolve('.'),contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {LivePdf} from './packages/plugins/office/src/pdf/Page.tsx';import {createPdfTask} from './packages/plugins/office/src/pdf/viewer.ts';window.createPdfTask=createPdfTask;const office={request:async(s,r)=>r.endpoint==='read'?structuredClone(window.saved):r.endpoint==='pdfBytes'?{revision:window.saved.revision,bytes:window.bytes}:r.endpoint==='lease'?{snapshot:window.saved,lease:{token:'test',clientId:r.clientId,expiresAt:Date.now()+30000}}:r.endpoint==='edit'?await(async()=>{window.saved={...window.saved,revision:2,state:{modelVersion:1,pages:[r.input.operations[0].page]}};window.bytes=await window.encodePdf(window.saved);return {revision:2,status:'committed'};})():{}};createRoot(document.getElementById('root')).render(React.createElement(LivePdf,{documentId:'pdf-1',sessionId:'session-a',office,visible:true,signal:new AbortController().signal,requestId:'one',onEditing:()=>{}}));`},bundle:true,platform:'browser',format:'iife',write:false,define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'deps',setup(b){b.onLoad({filter:/pdf\.worker\.min\.mjs$/},async a=>({contents:await readFile(a.path,'utf8'),loader:'text'}));b.onResolve({filter:/^(react(?:-dom)?|pdfjs-dist)(?:\/.*)?$/},a=>({path:req.resolve(a.path)}));}}]});
 const page=await browser.newPage({acceptDownloads:true});page.setDefaultTimeout(20000);await page.exposeFunction('encodePdf',async saved=>Buffer.from(await pdfBytes(saved)).toString('base64'));await page.route('http://127.0.0.1:19099/',r=>r.fulfill({contentType:'text/html',body:'<div id="root" style="display:flex;flex-direction:column;height:900px"></div>'}));await page.goto('http://127.0.0.1:19099/');await page.evaluate(({saved,bytes})=>{window.saved=saved;window.bytes=bytes},{saved:initial,bytes:Buffer.from(bytes0).toString('base64')});await page.addScriptTag({content:bundle.outputFiles[0].text});await page.getByRole('status').filter({hasText:'修订 0 · 预览已更新'}).waitFor();
 await page.evaluate(({saved,bytes})=>{window.saved=saved;window.bytes=bytes},{saved:changed,bytes:Buffer.from(bytes1).toString('base64')});await page.getByRole('status').filter({hasText:'修订 1 · 预览已更新'}).waitFor();
 const visibleGlyphs=await page.locator('canvas').evaluate(c=>{const ctx=c.getContext('2d');return Array.from({length:6},(_,i)=>{const p=ctx.getImageData(50+i*30,50,30,34).data;let ink=0;for(let j=0;j<p.length;j+=4)if(p[j]<180&&p[j+1]<180&&p[j+2]<180)ink++;return ink;});});assert.ok(visibleGlyphs.every(n=>n>30),`Chinese glyphs must visibly render: ${visibleGlyphs}`);
 const text=await page.evaluate(async()=>{const loading=window.createPdfTask(Uint8Array.from(atob(window.bytes),c=>c.charCodeAt(0)));const doc=await loading.task.promise;const p=await doc.getPage(1),content=await p.getTextContent();const text=content.items.map(i=>i.str).join('');await loading.destroy();return text;});assert.ok(text.includes('预算分析报告'));assert.ok(text.includes('收入 1000 万元'));
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载 PDF'}).click();const download=await pending;assert.deepEqual(await readFile(await download.path()),Buffer.from(bytes1));
 await page.getByRole('button',{name:'编辑本页文字'}).click();await page.getByRole('textbox',{name:'PDF 文本 body',exact:true}).fill('人工修改后的报告');await page.getByRole('button',{name:'完成编辑并保存'}).click();await page.getByRole('status').filter({hasText:'修订 2 · 预览已更新'}).waitFor();assert.equal(await page.evaluate(()=>window.saved.state.pages[0].elements[1].text),'人工修改后的报告');
 }finally{await browser.close();await rm(temp,{recursive:true,force:true});}});
