import { tokens } from './tokens.js';

export const navigationCss = `
.wd-sidebar{height:100%;min-width:0;background:${tokens.sidebar};color:${tokens.text};font:14px/22px "PingFang SC","Microsoft YaHei",sans-serif;display:flex;flex-direction:column;overflow:hidden;border-right:.5px solid ${tokens.border}}
.wd-sidebar *{box-sizing:border-box}.wd-sidebar button,.wd-sidebar input{font:inherit;color:inherit}
.wd-sidebar button{cursor:pointer}.wd-sidebar :focus-visible{outline:2px solid var(--dsw-alias-label-primary,#ddd);outline-offset:-2px}
.wd-sidebar .wd-top-tools{height:46px;display:flex;align-items:center;justify-content:flex-end;padding:0 14px;gap:8px;flex:none}
.wd-icon-button{border:0;background:transparent;width:32px;height:32px;display:inline-grid;place-items:center;color:var(--dsw-alias-label-tertiary,#aaa);border-radius:6px;flex:none}
.wd-sidebar .wd-brand-row{height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;margin-bottom:20px;flex:none}
.wd-sidebar .wd-brand-row strong{font-size:18px;font-weight:600}.wd-sidebar .wd-discover{background:var(--dsw-alias-interactive-bg-hover-solid,#343434);border:0;border-radius:18px;corner-shape:round;padding:4px 10px;display:flex;gap:3px;align-items:center;font-size:12px;color:var(--dsw-alias-label-tertiary,#aaa)}
.wd-sidebar .wd-main-nav{padding:0 10px;flex:none}.wd-nav-item{width:100%;display:flex;align-items:center;gap:4px;border:0;background:transparent;border-radius:8px;min-height:36px;margin:0 0 2px;padding:6px 8px;text-align:left;white-space:nowrap}
.wd-icon-slot{width:26px;display:inline-flex;align-items:center;flex:none;color:var(--dsw-alias-label-tertiary,#b9b9b9)}.wd-nav-item.is-active{background:${tokens.selected};font-weight:500}.wd-nav-item small{margin-left:auto;color:var(--dsw-alias-label-secondary,#a5a5a5);font-size:10px;font-weight:400}.wd-nav-item:disabled{cursor:not-allowed}.wd-sidebar button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover,#383838)}
.wd-sidebar .wd-list-scroll{overflow:auto;min-height:0;flex:1;padding:0 10px 20px}.wd-nav-group{margin-top:26px}.wd-nav-group summary{list-style:none;display:flex;align-items:center;gap:6px;color:var(--dsw-alias-label-secondary,#a5a5a5);font-size:12px;padding:0 10px 12px;cursor:pointer}.wd-nav-group summary::-webkit-details-marker{display:none}.wd-nav-group:not([open]) summary svg{transform:rotate(-90deg)}
.wd-sidebar .wd-task-row{border:0;background:transparent;border-radius:6px;width:100%;display:flex;align-items:center;text-align:left;gap:8px;padding:8px 10px;min-height:36px}.wd-task-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wd-task-row.is-active{background:var(--dsw-specific-sidebar-nav-item-active,#343434)}.wd-sidebar .wd-help{font-size:12px;line-height:20px;color:var(--dsw-alias-label-secondary,#a5a5a5);padding:0 10px;margin:0}.wd-sidebar .wd-filter{margin:0 12px 12px;display:flex;gap:4px}.wd-filter input{min-width:0;width:100%;background:var(--dsw-specific-input-major,#292929);border:.5px solid var(--dsw-alias-border-l2,#454545);border-radius:6px;padding:6px 8px}.wd-sidebar .wd-footer{padding:12px 10px;flex:none}.wd-sidebar.is-collapsed .wd-top-tools{padding:0;justify-content:center}.wd-sidebar.is-collapsed .wd-main-nav{padding:0 8px}.wd-sidebar.is-collapsed .wd-footer{padding:8px}.wd-sidebar.is-collapsed .wd-nav-item{justify-content:center;padding:6px}.wd-sidebar.is-collapsed .wd-icon-slot{width:auto}
.wd-modal-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:24px;background:var(--dsw-alias-bg-mask-1,rgba(0,0,0,.68));backdrop-filter:blur(2px)}
.wd-settings-modal{width:min(560px,calc(100vw - 32px));border:0;border-radius:20px;background:var(--dsw-alias-bg-layer-1,#202020);color:${tokens.text};box-shadow:var(--dsw-elevation-prominent,0 24px 80px rgba(0,0,0,.5));overflow:hidden}.wd-settings-modal header{display:flex;align-items:flex-start;justify-content:space-between;padding:28px 30px 18px}.wd-settings-modal h2{font-size:24px;line-height:32px;margin:3px 0 0}.wd-eyebrow{font-size:10px;letter-spacing:.18em;color:var(--dsw-alias-label-caption,#777)}.wd-modal-intro{margin:0;padding:0 30px 22px;color:var(--dsw-alias-label-tertiary,#aaa);line-height:24px}.wd-setting-list{margin:0 30px;border:.5px solid var(--dsw-alias-border-l1,#3b3b3b);border-radius:12px;overflow:hidden}.wd-setting-list>div{display:flex;align-items:center;gap:14px;padding:16px}.wd-setting-list>div+div{border-top:.5px solid var(--dsw-alias-border-l1,#383838)}.wd-setting-list svg{color:var(--dsw-alias-label-tertiary,#aaa);flex:none}.wd-setting-list span{display:flex;flex-direction:column;gap:2px}.wd-setting-list strong{font-size:14px}.wd-setting-list small{color:var(--dsw-alias-label-caption,#8f8f8f);font-size:12px}.wd-modal-note{margin:20px 30px 0;color:var(--dsw-alias-label-caption,#888);font-size:12px;line-height:20px}.wd-settings-modal footer{display:flex;justify-content:flex-end;gap:10px;margin-top:26px;padding:18px 30px;border-top:.5px solid var(--dsw-alias-border-l1,#343434)}.wd-button{border-radius:9px;padding:9px 16px;border:.5px solid var(--dsw-alias-border-l2,#464646)}.wd-button-secondary{background:transparent;color:var(--dsw-alias-label-primary,#ddd)}.wd-button-primary{background:var(--dsw-alias-button-primary-fill,#eee);color:var(--dsw-alias-label-primary-inverted,#171717);border-color:var(--dsw-alias-button-primary-fill,#eee);font-weight:600}.wd-button:hover{filter:brightness(1.08)}
@media(max-width:560px){.wd-sidebar .wd-nav-item,.wd-sidebar .wd-task-row,.wd-sidebar .wd-icon-button{min-height:44px}.wd-sidebar .wd-brand-row{margin-bottom:8px}.wd-sidebar .wd-main-nav{padding:0 6px}}
.wd-sidebar .wd-settings-modal .wd-button{flex:0 0 auto;width:auto}.wd-sidebar .wd-settings-modal .wd-button-secondary{background:transparent;color:var(--dsw-alias-label-primary,#ddd)}.wd-sidebar .wd-settings-modal .wd-button-primary{min-width:196px;background:var(--dsw-alias-button-primary-fill,#eee);color:var(--dsw-alias-label-primary-inverted,#171717);border-color:var(--dsw-alias-button-primary-fill,#eee);font-weight:600}.wd-sidebar .wd-settings-modal .wd-button-primary:hover:not(:disabled){background:var(--dsw-alias-button-primary-hover,#fff);color:var(--dsw-alias-label-primary-inverted,#111)}
`;
