export const officeCss = `
.wd-office-live{width:100%;max-width:100%;min-width:0;box-sizing:border-box;overflow:hidden;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;white-space:normal;line-height:1.4;display:flex;flex-direction:column;height:100%;min-height:0;color:var(--dsw-fg-default,#20242c);background:var(--dsw-bg-default,#f4f5f7);font-size:13px}
.wd-office-live .wd-office-docpicker,.wd-office-live .wd-office-toolbar,.wd-office-live .wd-office-format{display:flex;align-items:center;gap:8px;padding:5px 12px;min-height:34px;flex-shrink:0;border-bottom:1px solid var(--dsw-border-default,#dde1e7);background:var(--dsw-bg-elevated,#fff)}
.wd-office-live .wd-office-title{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:40px}
.wd-office-live .wd-office-status{margin-left:auto;font-size:12px;color:var(--dsw-fg-muted,#697386);white-space:nowrap}
.wd-office-live button:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *),.wd-office-live select:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *){font:inherit;color:inherit;background:transparent;border:1px solid var(--dsw-border-default,#d4d9e1);border-radius:5px;padding:3px 9px;min-height:28px;cursor:pointer}
.wd-office-live button:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *):hover:enabled{background:var(--dsw-bg-hover,#edf3ff)}
.wd-office-live button:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *):disabled,.wd-office-live select:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *):disabled{opacity:.45;cursor:default}
.wd-office-live .tiptap-toolbar{height:44px;max-height:44px;min-width:0;flex:0 0 44px;display:flex;align-items:center;gap:4px;box-sizing:border-box;flex-shrink:0;max-width:100%;min-height:44px;padding:4px 8px;background:var(--dsw-bg-elevated,#fff);border-bottom:1px solid var(--dsw-border-default,#dde1e7);overflow-x:auto;overscroll-behavior-x:contain;scrollbar-width:thin}
.wd-office-live .wd-office-ribbon fieldset,.wd-office-live .wd-office-ribbon-row{display:contents;border:0;margin:0;padding:0;min-width:0}
.wd-office-live .wd-office-toolgroup,.wd-office-live .tiptap-toolbar-group{display:flex;align-items:center;gap:2px;flex:0 0 auto;padding-right:6px;border-right:1px solid var(--dsw-border-default,#e5e7eb)}
.wd-office-live .wd-office-toolgroup:last-child{border-right:0}
.wd-office-live .wd-office-ribbon button,.wd-office-live .wd-office-ribbon select{border:0;border-radius:6px;height:32px;min-height:32px;padding:4px 6px;flex:0 0 auto;box-sizing:border-box;font-size:13px}
.wd-office-live .wd-office-ribbon button{display:inline-flex;align-items:center;justify-content:center;min-width:32px}
.wd-office-live .tiptap-button-icon{width:18px;height:18px;flex-shrink:0}
.wd-office-live .wd-office-ribbon button:hover:enabled,.wd-office-live .wd-office-ribbon select:hover:enabled{background:#f1f2f5}
.wd-office-live .wd-office-ribbon :is(button,select,input):focus-visible{outline:2px solid #6685dd;outline-offset:-2px}
.wd-office-live button:not(.workdsh-ppt-editor *, .workdsh-sheet-editor *)[aria-pressed=true]{color:#3159b9;background:#edf1fc;border-color:transparent}
.wd-office-live .wd-office-toolgroup select[aria-label="字体"]{width:108px}.wd-office-live .wd-office-toolgroup select[aria-label="字号"]{width:48px}.wd-office-live .wd-office-toolgroup select[aria-label="段落样式"]{width:80px}
.wd-office-live .wd-office-color{display:flex;align-items:center;gap:0;padding:0 2px;min-height:32px;box-sizing:border-box}
.wd-office-live .wd-office-color input{width:16px;height:20px;cursor:pointer;border:0;padding:0;background:transparent}
.wd-office-live .wd-office-color button{min-width:26px;padding:4px}
.wd-office-live fieldset:disabled .wd-office-color{opacity:.45}
.wd-office-live .wd-office-viewtools{display:flex;align-items:center;gap:2px;flex:0 0 auto;padding-right:6px;border-right:1px solid #e5e7eb}
.wd-office-live .wd-office-count{margin-left:auto;color:var(--dsw-fg-muted,#697386);font-size:12px}
.wd-office-live .wd-office-search{display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:8px 12px;flex-shrink:0;background:var(--dsw-bg-elevated,#fff);border-bottom:1px solid var(--dsw-border-default,#dde1e7)}
.wd-office-live .wd-office-search input{font:inherit;min-width:80px;width:130px;background:transparent;color:inherit;border:1px solid var(--dsw-border-default,#d4d9e1);border-radius:5px;padding:5px 8px}
.wd-office-live .wd-office-writing ul{list-style:disc;padding-left:28px;margin:8px 0 16px}.wd-office-live .wd-office-writing ol{list-style:decimal;padding-left:28px;margin:8px 0 16px}.wd-office-live .wd-office-writing li{display:list-item}.wd-office-live .wd-office-writing li p{margin-bottom:6px}
.wd-office-live .wd-office-docpicker select{flex:1;min-width:0;border:0}
.wd-office-live .wd-office-paper-scroll{flex:1;overflow:auto;padding:24px;min-height:0;background:var(--dsw-bg-subtle,#edf0f4)}
.wd-office-live .wd-office-paper{background:#fff;color:#222b39;max-width:794px;min-height:850px;margin:0 auto;padding:52px 56px;box-shadow:0 2px 10px #00000012;box-sizing:border-box}
.wd-office-live .wd-office-writing{outline:none;white-space:pre-wrap;overflow-wrap:anywhere;font-family:system-ui,sans-serif;font-size:16px;line-height:1.85;min-height:700px}
.wd-office-live .wd-office-writing p{margin:0 0 12px}.wd-office-live .wd-office-writing h1{font-size:30px;line-height:1.4;margin:28px 0 18px}.wd-office-live .wd-office-writing h2{font-size:24px;margin:24px 0 14px}.wd-office-live .wd-office-writing h3{font-size:20px;margin:20px 0 12px}
.wd-office-live .wd-office-problem{padding:8px 12px;color:#9b3824;background:#fff2e9;flex-shrink:0}
.wd-office-live .wd-office-import-note{padding:6px 12px;font-size:12px;line-height:1.6;background:#fff7e6;color:#6d531a;flex-shrink:0;border-bottom:1px solid #eadfc5}
.wd-office-live .wd-office-empty{margin:auto;padding:32px;max-width:430px;line-height:1.8}
.wd-office-live .wd-office-image-upload{position:relative;cursor:pointer;white-space:nowrap;padding:4px 6px}.wd-office-live .wd-office-image-upload input{position:absolute;inset:0;opacity:0;width:100%;cursor:pointer}
.wd-office-live fieldset:disabled .wd-office-image-upload{opacity:.45;cursor:default}
.wd-office-live .wd-office-writing .tableWrapper{overflow-x:auto;margin:16px 0}.wd-office-live .wd-office-writing table{border-collapse:collapse;table-layout:fixed;width:100%;overflow:hidden}.wd-office-live .wd-office-writing :is(td,th){border:1px solid #c7ced8;min-width:25px;padding:6px 8px;position:relative;vertical-align:top;box-sizing:border-box}.wd-office-live .wd-office-writing th{background:#f0f3f8;font-weight:600}.wd-office-live .wd-office-writing .selectedCell:after{position:absolute;inset:0;background:#6586d533;content:"";pointer-events:none}.wd-office-live .wd-office-writing .column-resize-handle{position:absolute;right:-2px;top:0;bottom:0;width:4px;background:#6685dd;pointer-events:none}.wd-office-live .resize-cursor{cursor:col-resize}.wd-office-live .wd-office-writing img{max-width:100%;height:auto}.wd-office-live .wd-office-writing .ProseMirror-selectednode{outline:2px solid #6685dd}
.wd-office-live [data-resize-container]:has(img[data-alignment="center"]){justify-content:center}.wd-office-live [data-resize-container]:has(img[data-alignment="right"]){justify-content:flex-end}
.wd-office-live [data-resize-wrapper]{width:fit-content;max-width:100%}.wd-office-live [data-resize-handle]{width:8px;height:8px;background:#fff;border:1px solid #6685dd;box-sizing:border-box;opacity:0}.wd-office-live [data-resize-wrapper]:hover [data-resize-handle],.wd-office-live .ProseMirror-selectednode [data-resize-handle]{opacity:1}.wd-office-live [data-resize-handle="bottom-right"],.wd-office-live [data-resize-handle="top-left"]{cursor:nwse-resize}.wd-office-live [data-resize-handle="bottom-left"],.wd-office-live [data-resize-handle="top-right"]{cursor:nesw-resize}
.wd-office-live .wd-office-chart{box-sizing:border-box;margin:20px 0;padding:12px 14px 8px;border:1px solid #d8dee8;border-radius:8px;background:#fff;overflow:hidden}.wd-office-live .wd-office-chart[data-alignment="center"]{margin-left:auto;margin-right:auto}.wd-office-live .wd-office-chart[data-alignment="right"]{margin-left:auto}.wd-office-live .wd-office-chart figcaption{text-align:center;font-weight:600;font-size:15px;margin-bottom:2px}.wd-office-live .wd-office-chart svg{display:block;width:100%;height:auto;max-height:520px}.wd-office-live .wd-office-chart-legend{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;color:#475569;font-size:12px}.wd-office-live .wd-office-chart-legend span{display:inline-flex;align-items:center;gap:5px}.wd-office-live .wd-office-chart-legend i{width:10px;height:10px;border-radius:2px}.wd-office-live .wd-office-writing .wd-office-chart.ProseMirror-selectednode{outline:2px solid #6685dd;outline-offset:2px}
@media(max-width:900px){.wd-office-live .wd-office-paper-scroll{padding:12px}.wd-office-live .wd-office-paper{padding:32px 24px}.wd-office-live .wd-office-title{max-width:160px}}
`;
