export const css = `
header:has(.wd-activity){position:relative;padding-bottom:66px} .wd-activity{position:absolute;left:0;right:0;bottom:12px;width:calc((100% - 40px)/2);max-width:560px;margin-inline:auto;container-type:inline-size;container-name:wd-activity;color:var(--dsw-alias-text-primary,#ddd);font:14px/1.4 system-ui;flex-shrink:0}
.wd-activity-bar{position:relative;isolation:isolate;box-sizing:border-box;height:46px;display:flex;align-items:center;gap:18px;border:1px solid #ffffff14;corner-shape:round;border-radius:12px;padding:0 14px;background:linear-gradient(110deg,#23282e 0%,#1e2227 38%,#1d2024 100%);box-shadow:inset 0 1px 0 #ffffff04;min-width:0}
.wd-activity-people{display:flex;align-items:center;flex-shrink:0}.wd-activity-face{position:relative;display:grid;place-items:center;width:30px;height:30px;corner-shape:round;border-radius:50%;background:linear-gradient(140deg,#3a5369,#273646);border:1px solid #c8e1f12e;color:#e4ecf3;font-weight:500;overflow:hidden;flex-shrink:0}.wd-activity-face+.wd-activity-face{margin-left:-8px}.wd-activity-face img{width:100%;height:100%;object-fit:cover;corner-shape:round;border-radius:50%}.wd-activity-face svg{width:22px;height:22px;overflow:visible}.wd-activity-eyes{transform-box:fill-box;transform-origin:center}
.wd-activity-title{flex-shrink:0;color:#e0e4e9;letter-spacing:.03em}.wd-activity-divider{width:1px;height:19px;background:#50565d;flex:none}.wd-activity-copy{display:flex;align-items:center;overflow:hidden;white-space:nowrap;flex:1;min-width:0}.wd-activity-member{overflow:hidden;text-overflow:ellipsis;min-width:0;color:#d4d8dd}.wd-activity-member+.wd-activity-member{margin-left:24px;padding-left:24px;border-left:1px solid #50565d}.wd-activity-member-name{color:#a6cbdf}.wd-activity-summary{display:flex;align-items:center;gap:8px;color:#9ca6b0;font-size:11px;flex:none}.wd-activity-time{color:#999;font-variant-numeric:tabular-nums;flex-shrink:0}
.wd-activity button{border:0;background:transparent;color:inherit;cursor:pointer;font:inherit}.wd-activity button:focus-visible{outline:2px solid #6698da;outline-offset:2px}.wd-activity-toggle{display:grid;place-items:center;width:28px;height:28px;border-radius:6px!important;flex:none}.wd-activity-toggle:hover{background:#ffffff09}.wd-activity-toggle svg{width:20px;height:20px}.wd-activity-status{width:6px;height:6px;background:#759acf;corner-shape:round;border-radius:50%;flex-shrink:0}
.wd-activity[data-phase=completed] .wd-activity-status{background:#75b392}.wd-activity[data-phase=failed] .wd-activity-status,.wd-activity[data-phase=interrupted] .wd-activity-status,.wd-activity[data-phase=waiting] .wd-activity-status{background:#cba56b}
.wd-activity[data-motion=true][data-phase=working] .wd-activity-face:first-child{animation:wd-activity-breathe 3s ease-in-out infinite}.wd-activity[data-motion=true][data-phase=working] .wd-activity-status{animation:wd-activity-breathe 2s ease-in-out infinite}.wd-activity[data-motion=true][data-phase=completed] .wd-activity-face:first-child{animation:wd-activity-nod .65s ease-in-out 1}.wd-activity[data-motion=true][data-long=true][data-phase=working] .wd-activity-face:first-child{animation-duration:5s}
.wd-activity-details{position:absolute;top:54px;left:0;right:0;z-index:30;padding:14px;border:1px solid #3a3a3a;border-radius:10px;background:#202020;box-shadow:0 8px 25px #0006;max-height:320px;overflow:auto}.wd-activity-details header{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.wd-activity-details p{margin:6px 0;color:#aaa}.wd-activity-person{display:flex;align-items:center;gap:9px;padding:7px 0;border-top:1px solid #333}.wd-activity-person .wd-activity-name{flex:1}.wd-activity-details label{display:flex;align-items:center;gap:8px;margin-top:10px}.wd-activity-details small{color:#999}.wd-activity-details a{color:#9bbce4}
.wd-activity-working{display:flex;align-items:center;gap:4px;flex:none;padding:0 3px}.wd-activity-working i{width:4px;height:4px;background:#a4cde4;corner-shape:round;border-radius:50%;opacity:.75}
.wd-activity-motion{opacity:0;overflow:hidden;padding:0!important;display:grid;place-items:center;width:0;transition:width .16s ease,opacity .16s ease;height:26px;border-radius:5px!important;color:#8e9ca9!important;flex:none}.wd-activity-bar:hover .wd-activity-motion,.wd-activity-bar:focus-within .wd-activity-motion,.wd-activity[data-motion=false] .wd-activity-motion{width:24px;opacity:.65}.wd-activity-motion svg{width:15px;height:15px}.wd-activity-motion:hover{opacity:1;background:#ffffff0b;color:#c2d9ea!important}
.wd-activity[data-motion=true][data-phase=working] .wd-activity-working i{animation:wd-activity-wave 1.3s ease-in-out infinite}.wd-activity[data-motion=true][data-phase=working] .wd-activity-working i:nth-child(2){animation-delay:.16s}.wd-activity[data-motion=true][data-phase=working] .wd-activity-working i:nth-child(3){animation-delay:.32s}
.wd-activity[data-motion=true][data-phase=working] .wd-activity-eyes{animation:wd-activity-blink 4.5s ease-in-out infinite}.wd-activity[data-motion=true][data-phase=working] .wd-activity-face:first-child{box-shadow:0 0 0 2px #78b7df12,0 0 12px #6cb0e825}
header:has(.wd-activity[data-team=true]){padding-bottom:76px}
.wd-activity[data-team=true] .wd-activity-bar{height:56px;gap:18px;padding:0 18px;border-radius:16px}
.wd-activity[data-team=true] .wd-activity-people{gap:8px}
.wd-activity[data-team=true] .wd-activity-face{width:36px;height:36px;border-color:#9ac3ed66}
.wd-activity[data-team=true] .wd-activity-face+.wd-activity-face{margin-left:0}
.wd-activity-copy{display:flex;flex-direction:column;align-items:flex-start;gap:3px}
.wd-activity-title{font-size:11px;color:#a9b3c0;max-width:100%;overflow:hidden;text-overflow:ellipsis}
.wd-activity-action{font-size:14px;color:#e6e9ee;max-width:100%;overflow:hidden;text-overflow:ellipsis}
.wd-activity[data-team=true] .wd-activity-action{font-weight:500}
.wd-activity[data-team=true] .wd-activity-details{top:64px}
.wd-activity[data-team=true][data-motion=true][data-phase=working] .wd-activity-face{animation:none;box-shadow:none}
.wd-activity[data-team=true] .wd-activity-face[data-active=true]{border-color:#65dceb;box-shadow:0 0 0 2px #65dceb16,0 0 12px #65dceb33}
.wd-activity[data-team=true][data-motion=true][data-phase=working] .wd-activity-face[data-active=true]{animation:wd-activity-breathe 3s ease-in-out infinite}
@container wd-activity (max-width:400px){.wd-activity[data-team=true] .wd-activity-face{width:28px;height:28px}.wd-activity-title{display:block!important}.wd-activity[data-team=true] .wd-activity-bar{gap:10px;padding:0 10px}}
@property --wd-activity-angle{syntax:"<angle>";initial-value:0deg;inherits:false}
.wd-activity[data-phase=working] .wd-activity-bar::before{content:"";position:absolute;inset:-1px;border-radius:inherit;padding:1.5px;pointer-events:none;background:conic-gradient(from var(--wd-activity-angle),#78d5ff 0deg,#91afff 65deg,#bb91ec 120deg,#f0a0c6 175deg,#e8bf96 215deg,#86dfd5 285deg,#78d5ff 360deg);mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);mask-composite:exclude;opacity:.82;filter:drop-shadow(0 0 3px #88b6e32a)}
.wd-activity[data-motion=true][data-phase=working] .wd-activity-bar::before{animation:wd-activity-orbit 5s linear infinite}
@keyframes wd-activity-orbit{to{--wd-activity-angle:360deg}}
@keyframes wd-activity-wave{0%,70%,100%{transform:translateY(0);opacity:.35}35%{transform:translateY(-3px);opacity:1}}@keyframes wd-activity-blink{0%,43%,48%,100%{transform:scaleY(1)}45%,46%{transform:scaleY(.12)}}
@keyframes wd-activity-breathe{0%,100%{opacity:.8;transform:translateY(0)}50%{opacity:1;transform:translateY(-2px)}}@keyframes wd-activity-nod{0%,100%{transform:translateY(0)}50%{transform:translateY(2px)}}
@media(prefers-reduced-motion:reduce){.wd-activity *,.wd-activity *::before,.wd-activity *::after{animation:none!important;transition:none!important}}
@container wd-activity (max-width:640px){.wd-activity-summary{display:none}.wd-activity-member+.wd-activity-member{margin-left:14px;padding-left:14px}}
@container wd-activity (max-width:400px){.wd-activity-title,.wd-activity-divider,.wd-activity-member+.wd-activity-member{display:none}}
@media(max-width:900px){.wd-activity-summary{display:none}.wd-activity-member+.wd-activity-member{margin-left:14px;padding-left:14px}}
@media(max-width:600px){.wd-activity{left:10px;right:10px;width:auto;max-width:560px}.wd-activity-title,.wd-activity-divider,.wd-activity-member+.wd-activity-member{display:none}.wd-activity-time{font-size:11px}}
`;
