import React from 'react';
import {Undo2,Redo2,Plus,Type,AlignLeft,Shapes,Table2,ChartNoAxesCombined,ZoomIn,ZoomOut,Scan,Grid2X2,Ruler,Search,Image,PanelLeft,Sparkles,Layers,Trash2} from 'lucide-react';
import type {ToolbarProps,SlideCanvasProps} from 'pptx-react-viewer';
import './ribbon.css';
const Action=({name,icon:Icon,onClick,disabled=false}:{name:string,icon:any,onClick:()=>void,disabled?:boolean})=><button className="ribbon-action" onClick={onClick} disabled={disabled} title={name}><Icon size={23}/><span>{name}</span></button>;
export function Ribbon({p,canvas,onMore,onAddSlide}:{p:ToolbarProps,canvas:SlideCanvasProps,onMore:()=>void,onAddSlide:()=>void}){
 const [tab,setTab]=React.useState('开始');

 const text=!!p.selectedElement&&(p.selectedElement.type==='text'||'text' in p.selectedElement);
 return <section className="work-ribbon" aria-label="演示文稿工具栏"><div className="ribbon-document">{p.fileName??'演示文稿'}</div><div className="ribbon-tabs" role="tablist">{['开始','插入','切换','动画','视图'].map(name=><button key={name} role="tab" aria-selected={tab===name} onClick={()=>setTab(name)}>{name}</button>)}<button className="ribbon-more" onClick={onMore}>全部工具</button></div><div className="ribbon-body" role="tabpanel" aria-label={tab}>
 {tab==='开始'&&<><div className="ribbon-group"><Action name="撤销" icon={Undo2} onClick={p.onUndo} disabled={!p.canUndo}/><Action name="重做" icon={Redo2} onClick={p.onRedo} disabled={!p.canRedo}/></div><div className="ribbon-group"><Action name="添加页面" icon={Plus} onClick={onAddSlide}/><details className="ribbon-menu"><summary><Type size={23}/><span>字体 ▾</span></summary><div><button disabled={!text} onClick={()=>canvas.onFormatText?.({bold:!p.selectedElement?.textStyle?.bold})}>加粗</button><button disabled={!text} onClick={()=>canvas.onFormatText?.({italic:!p.selectedElement?.textStyle?.italic})}>斜体</button><label>字号<input type="number" min="6" max="200" defaultValue="24" disabled={!text} onChange={e=>{const n=Number(e.target.value);if(n>=6&&n<=200)canvas.onFormatText?.({fontSize:n})}}/></label></div></details><details className="ribbon-menu"><summary><AlignLeft size={23}/><span>段落 ▾</span></summary><div>{[['left','左对齐'],['center','居中'],['right','右对齐']].map(([id,name])=><button key={id} disabled={!text} onClick={()=>canvas.onFormatText?.({alignment:id as any})}>{name}</button>)}</div></details></div></>}
 {tab==='插入'&&<><Action name="空白页面" icon={Plus} onClick={onAddSlide}/><Action name="文本框" icon={Type} onClick={p.onAddTextBox}/><Action name="形状" icon={Shapes} onClick={p.onAddShape}/><button className="ribbon-action" disabled title="图片文件选择还未接入此组合界面"><Image size={23}/><span>图片</span></button><Action name="表格" icon={Table2} onClick={p.onAddTable}/><details className="ribbon-menu"><summary><ChartNoAxesCombined size={23}/><span>图表 ▾</span></summary><div>{[['bar','柱状图'],['line','折线图'],['pie','饼图'],['doughnut','环形图'],['area','面积图']].map(([id,name])=><button key={id} onClick={e=>{p.onAddChart?.(id as any);e.currentTarget.closest('details')?.removeAttribute('open')}}>{name}</button>)}</div></details></>}
 {tab==='切换'&&<><div className="ribbon-group">{[['none','无切换'],['fade','淡出淡入'],['push','推入'],['wipe','擦除']].map(([id,name])=><button key={id} className="ribbon-action" aria-pressed={(p.activeSlide?.transition?.type??'none')===id} onClick={()=>p.onTransitionChange({type:id as any})}><Layers size={23}/><span>{name}</span></button>)}</div><label className="ribbon-check"><span>持续时间（秒）</span><input aria-label="切换持续时间" type="number" min="0.1" max="10" step="0.1" value={(p.activeSlide?.transition?.durationMs??500)/1000} onChange={e=>{const n=Number(e.target.value);if(n>=0.1&&n<=10)p.onTransitionChange({durationMs:n*1000})}}/></label><Action name="应用到全部" icon={Layers} onClick={p.onApplyTransitionToAll}/></>}
 {tab==='动画'&&<><div className="ribbon-group">{[['fadeIn','淡入'],['flyIn','飞入'],['zoomIn','缩放进入']].map(([id,name])=><Action key={id} name={name} icon={Sparkles} disabled={!p.selectedElement} onClick={()=>p.onAddAnimation?.(id,'entrance')}/>)}</div><Action name="脉冲强调" icon={Sparkles} disabled={!p.selectedElement} onClick={()=>p.onAddAnimation?.('pulse','emphasis')}/><Action name="淡出退出" icon={Sparkles} disabled={!p.selectedElement} onClick={()=>p.onAddAnimation?.('fadeOut','exit')}/><Action name="移除动画" icon={Trash2} disabled={!p.selectedElement} onClick={()=>p.onRemoveAnimation?.()}/></>}
 {tab==='视图' &&<><Action name="放大" icon={ZoomIn} onClick={p.onZoomIn}/><Action name="缩小" icon={ZoomOut} onClick={p.onZoomOut}/><Action name="适应窗口" icon={Scan} onClick={p.onZoomToFit}/><label className="ribbon-check"><Grid2X2 size={23}/><span><input type="checkbox" checked={p.showGrid} onChange={e=>p.onSetShowGrid(e.target.checked)}/>网格线</span></label><label className="ribbon-check"><Ruler size={23}/><span><input type="checkbox" checked={p.showRulers} onChange={e=>p.onSetShowRulers(e.target.checked)}/>标尺</span></label></>}
 </div></section>;
}
